[project]
name = "pentest_organizer"
version = "0.1.0"
description = "An application for organizing stages of penetration testing process"
authors = [
    {name = "Wayne Lai", email = "waynelai01011231@gmail.com"},
]
dependencies = [
    "Flask>=3.0.3",
    "sqlalchemy>=2.0.32",
]
requires-python = ">=3.7"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pytest.ini_options]
pythonpath = "src"

